version: '3.9'
services:
  web:
    build: .
    entrypoint: /entrypoint.sh
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/opt/webapp
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: database.env
